---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  values: |-
    replicas: 1
    image:
      repository: nextcloud
      tag: latest
      pullPolicy: IfNotPresent
    internalDatabase:
      enabled: true
      name: nextcloud
    externalDatabase:
      enabled: false
    mariadb:
      enabled: false
    persistence:
      enabled: false
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
  interval: 1m0s